// Generate src/low/version.ts from package.json's version so the SDK's
// User-Agent always reports the published package version. This runs as part of
// `pnpm build`; the publish workflow sets package.json to the release-tag
// version before building (tag-driven versioning), so the published bundle
// carries that version instead of a hand-kept constant that silently drifts.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("..", import.meta.url);
const pkg = JSON.parse(readFileSync(new URL("package.json", root), "utf8"));
const out = fileURLToPath(new URL("src/low/version.ts", root));

const body = `// GENERATED by scripts/gen-version.mjs from package.json — do not edit.
export const SDK_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(out, body);
console.log(`Wrote src/low/version.ts (SDK_VERSION = ${pkg.version})`);
